name: Cek Layanan Indonesia

on:
  schedule:
    - cron: '*/10 * * * *'  # Setiap 10 menit
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Jalankan pengecekan
        run: |
          pip install requests
          python check_services.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
