name: Cek Layanan Indonesia

on:
  schedule:
    - cron: '*/30 * * * *'  # setiap 30 menit
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      PYTHONIOENCODING: utf-8

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install requests
      run: pip install requests

    - name: Jalankan pengecekan
      run: python check_services.py
